# config/packages/security.yaml
security:
  encoders:
      # use your user class name here
      App\Entity\Player:
          # bcrypt or argon2i are recommended
          # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
          algorithm: bcrypt
          cost: 12
  role_hierarchy:
      ROLE_ADMIN:       ROLE_USER

  providers: 
    main:
      entity:
        class: App\Entity\Player
        property: username


  access-control:
    - { path: /delete/, roles: ROLE_ADMIN}
    - { path: /disable/, roles: ROLE_ADMIN}
    - { path: ^/admin, roles: ROLE_ADMIN }