<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCtp12ze\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCtp12ze/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCtp12ze.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCtp12ze\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCtp12ze\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ctp12ze',
    'container.build_id' => 'bffa6954',
    'container.build_time' => 1547540564,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCtp12ze');
